### ISSUE TITLE
Missing placeholder class for input field

### ISSUE THREAD

**Issue by Deepansharora27** [product-ride/styled-wind#13]
**Describe the bug**
When trying to apply the placeholder class property and applying color attribute to the input field , it is not yielding the expected output.

**Expected behavior**
Applying any of the placeholder class attributes like `placeholder-pink-400`or for any color for that matter should change the color of the placeholder of the input field.

**Screenshots**
![Screenshot 2020-11-24 at 1 48 20 AM](https://user-images.githubusercontent.com/43300955/100011339-954dad80-2df7-11eb-9e07-3d2a2458daea.png)

![Screenshot 2020-11-24 at 1 52 11 AM](https://user-images.githubusercontent.com/43300955/100011444-c201c500-2df7-11eb-8527-7dae50c2dafa.png)

**Desktop **

- OS: MacOS
- Browser: Firefox Developer Edition
- Version: 84.0b3

**Comment by jyash97** [comment]
Hey @Deepansharora27  👋 

Looks like you are not using the class correctly. Can you try:

```
styled.input`
  .placeholder-pink-500;
`;
```

`Note:` You need to add `.` before the classname.

**Comment by Deepansharora27** [comment]
@jyash97 I know there's a mistake in my screenshot , but even if you prefix `.` to it , it's not working .
I even had a discussion with @vilvaathibanpb and he also said that it's a bug , not supporting placeholder class

**Comment by jyash97** [comment]
I did check this on CodeSandbox and it did work for me. Check below screenshots: 

![image](https://user-images.githubusercontent.com/22376783/100703524-b4d17100-33c9-11eb-9f82-64e56b33154e.png)

![image](https://user-images.githubusercontent.com/22376783/100703651-f8c47600-33c9-11eb-9b21-77de1769c1cd.png)

I also confirmed with red and yellow and seems to be working.

**Comment by Deepansharora27** [comment]
@jyash97 Tried it out again just now , it is now working for me as well. I think there might be some other issue earlier.
Thanks 
Closing this issue then
