### ISSUE TITLE
Getting a TypeError when I am trying to use .bg-shadow tailwind class 

### ISSUE THREAD

**Issue by sudharsangs** [product-ride/styled-wind#2]
The below is the component I was trying to define
```javascript
const StyledContainer = styled.div`
.max-w-lg;
.text-white;
.bg-green-300;
.bg-opacity-25;
.p-10; 
.rounded; 
.overflow-hidden; 
.shadow-lg;
`;
```

This is the error I am getting 
![image](https://user-images.githubusercontent.com/30121484/86538582-74ea8880-bf14-11ea-8d61-88bdb8784e24.png)

Operating System: Linux Ubuntu 
Browser: Mozilla Firefox

**Comment by ameerthehacker** [comment]
fixed in #3
