### ISSUE TITLE
Height dynamic property is using values from width

### ISSUE THREAD

**Issue by BA1RY** [product-ride/styled-wind#22]
**Describe the bug**
Height dynamic property class is using width's values.
For example: `.h-screen` is parsed as `height: 100vw`.

**Expected behavior**
 `.h-screen` is parsed as `height: 100vh`

**Screenshots**
![h](https://user-images.githubusercontent.com/10570968/100541553-b3d5fd80-326a-11eb-9f4f-c9fbbab6d825.png)

**Solution**
It should be `this.config.theme.height` instead of `this.config.theme.width` .
![height](https://user-images.githubusercontent.com/10570968/100541624-2cd55500-326b-11eb-85cf-8ebd2bd147fd.png)

**Desktop (please complete the following information):**

- OS: Manjaro
- Browser: Brave
- Version: v0.0.0-beta.10

**Comment by BA1RY** [comment]
@vilvaathibanpb I'll be making PR for the same

**Comment by vilvaathibanpb** [comment]
Sure @BA1RY go ahead please

**Comment by ameerthehacker** [comment]
@BA1RY good find

**Comment by BA1RY** [comment]
_Posting this from chat for reference here_
I tried making the change I mentioned above. It broke the `height` property.  Test case for `.h-10/12` resulted in `height: undefined` as there is no class in tailwind for the same.  `.h-5/6` also resulted in `undefined` but it has a tailwind class. It's mostly because we haven't defined values for height property. Should we manually define those values in the config files or is there any other method for this?

`width` property style definition
![image](https://user-images.githubusercontent.com/10570968/100768001-68655000-3420-11eb-88b4-ff93745eb4fb.png)

`height` property style definition
![image](https://user-images.githubusercontent.com/10570968/100768254-ab272800-3420-11eb-9248-b452e8bc104c.png)

**Comment by BA1RY** [comment]
Hi @vilvaathibanpb @ameerthehacker I've made a PR. New additional spacing values and few additional normal/min/max height/width classes from latest tailwind have been added.  Please have a look at it. Thanks :smile:
