### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by vilvaathibanpb** [product-ride/styled-wind#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Missing classes:

.z-50
.min-h-4
.cursor-pointer - issue, works only when added last

**Comment by sudharsangs** [comment]
@vilvaathibanpb there is no tailwind class named `min-h-4`. The possible classes are handled already. For possible tailwind class names for minimum height please refer [here](https://tailwindcss.com/docs/min-height). For the other 2 class names, I have raised a [PR](https://github.com/product-ride/styled-wind/pull/7)
